"""
Management command to seed all 240 questions from the JS data into SQLite.
Run: python manage.py load_questions
"""
import json
from django.core.management.base import BaseCommand
from quiz.models import Test, Question


# ── Raw question data (converted from questions.js) ──────────────────────────
# This is the canonical data for all 4 practice tests.
TESTS_DATA = {
    "test1": {
        "name": "Practice Test 1",
        "questions": [
            {"id":1,"question":"Create Incident, Password Reset, and Report outage: what do these services in the Service Catalog have in common?","options":["They direct the user to a record producer","They direct the user to a catalog property","They direct the user to a catalog UI policy","They direct the user to a catalog client script"],"answer":[0],"explanation":"These catalog items use Record Producers to generate records (like Incident). A record producer is a form used in the Service Catalog to create task-based records while collecting necessary information from users.","multi":False},
            {"id":2,"question":"On a Form header, what is the three bar icon called?","options":["Pancake icon","Hamburger icon","Cake icon","Form Context Menu"],"answer":[3],"explanation":"In ServiceNow, the three-line icon in a form header opens the Form Context Menu, which contains options like Configure, Export, View, etc.","multi":False},
            {"id":3,"question":"What do you need to do before you can use an Application-based trigger in your flow?","options":["Activate application trigger spoke","Activate application plugins only","Activate trigger security rules","Activate application spoke, and plug-ins as needed","Assign Application trigger role [sn_app_trigger_write] to SME"],"answer":[3],"explanation":"Application-based triggers rely on spokes and required plug-ins. Without activating them, the trigger will not be available in Flow Designer.","multi":False},
            {"id":4,"question":"Your customer requires the ability to monitor which users are performing impersonations in their instance. What would you do to meet that requirement?","options":["From User icon, select Elevate Roles","On the Impersonator role record, right click and select Create Log","Activate the glide.sys.log_impersonation prop","Add the role Log Write [sn_log_write] to the Impersonator Group","Create user update set for impersonation tracking"],"answer":[2],"explanation":"Setting the system property glide.sys.log_impersonation to true enables logging of impersonation activities.","multi":False},
            {"id":5,"question":"A knowledge article must be which of the following states to display to a user?","options":["Published","Review","Draft","Retired"],"answer":[0],"explanation":"Only articles in the Published state are visible to end users.","multi":False},
            {"id":6,"question":"Which one of the following is an accurate list of changes that are captured in an Update Set?","options":["Changes made to: tables, forms, scheduled jobs, and client scripts","Changes made to: tables, forms, groups, and configuration items (CIs)","Changes made to: table, forms, views, and fields","Changes made to: tables, forms, Business Rules, and data records"],"answer":[2],"explanation":"Update Sets capture configuration changes (metadata), not actual data like groups or CI records.","multi":False},
            {"id":7,"question":"Which of the following protects applications by identifying and restricting access to available files and data?","options":["Application Scope","Application Configuration","Access Control Rules","Verbose Log"],"answer":[0],"explanation":"Application Scope restricts cross-application access to tables, scripts, and other resources.","multi":False},
            {"id":8,"question":"An IT manager is responsible for the Network and Hardware assignment groups. The manager cannot see any tasks on the Service Desk > My Groups Work list. What could explain this?","options":["The list shows active work tasks that are not yet assigned","The manager is not a member of the Service Desk group","The manager does not have the itil role","The manager is not a member of the Network and Hardware groups"],"answer":[3],"explanation":"My Groups Work shows tasks assigned to groups where the user is a member. If the manager is not a member of those groups, they won't see those tasks.","multi":False},
            {"id":9,"question":"Which application is used primarily to load data into ServiceNow?","options":["Import Set","System Import Sets","Import Management","Import Hub"],"answer":[1],"explanation":"The System Import Sets application loads external data into staging tables for transformation.","multi":False},
            {"id":10,"question":"What options are available to choose from in the 'When' field in the Business Rule? (Select 2 answers)","options":["Insert","Update","Before","After"],"answer":[2,3],"explanation":"The 'When' field determines execution timing: Before, After, Async, or Display.","multi":True},
            {"id":11,"question":"A new employee joins the IT department. What would you do? (Select 3 answers)","options":["Modify ACL","Add roles to the user","Add User Account to Hardware group","Create User Account","Add User Account to Software group","Add User Account to Network group"],"answer":[2,3,5],"explanation":"Create User Account, add to Hardware group, add to Network group.","multi":True},
            {"id":12,"question":"When using the Load Data and Transform Map process, what is the Mapping Assist used for?","options":["Mapping fields using the Import Log","Mapping fields using an SLA","Mapping fields using Transform History","Mapping fields using a Field Map"],"answer":[3],"explanation":"Mapping Assist helps create field mappings between source and target tables using a Field Map.","multi":False},
            {"id":13,"question":"Which tool should be used to populate commonly used fields in a form?","options":["Template","Reference Qualifier","Formatter","Assignment Rule"],"answer":[0],"explanation":"Templates pre-populate fields with predefined values, saving time on repetitive data entry.","multi":False},
            {"id":14,"question":"What is the Import Set Table?","options":["A table where data will be placed, post-transformation","A repository for Update Set information","A table that determines relationships","A staging area for imported records"],"answer":[3],"explanation":"Import Set tables temporarily hold imported data before transformation to the target table.","multi":False},
            {"id":15,"question":"Which term best describes something that is created, has work performed upon it, and is eventually moved to a state of closed?","options":["report","flow","task","event"],"answer":[2],"explanation":"A Task follows lifecycle states from creation through work to a closed state.","multi":False},
            {"id":16,"question":"Which one of the following statements describes the purpose of a Service Catalog flow?","options":["A flow generates: item variable types, tasks, and notifications","A flow generates: item variable types, tasks, and approvals","A flow drives complex fulfillment processes and sends notifications to defined users or groups","A flow cannot send notifications but drives complex fulfillment processes"],"answer":[2],"explanation":"Catalog flows automate fulfillment steps like approvals, tasks, and notifications.","multi":False},
            {"id":17,"question":"IntegrationHub enables execution of third-party APIs as a part of a flow. These integrations are referred to as","options":["a spoke","an action","an integration step","a connection"],"answer":[0],"explanation":"IntegrationHub uses Spokes to integrate with third-party systems like Slack, Jira, etc.","multi":False},
            {"id":18,"question":"What are examples of Core tables in the ServiceNow platform?","options":["Team, Party, Awards","User, Task, Incident","Configuration, Connect, Chat","Work, Caller, Timecard"],"answer":[1],"explanation":"User [sys_user], Task [task], and Incident [incident] are foundational core tables.","multi":False},
            {"id":19,"question":"Which role can manage multiple knowledge bases?","options":["sn_kb_admin","knowledge_admin","kb_admin","knowledge_base_admin"],"answer":[1],"explanation":"The knowledge_admin role provides the ability to manage all knowledge bases.","multi":False},
            {"id":20,"question":"What is the primary application used to load data into ServiceNow?","options":["Configuration","Service Level Management","System Import Sets","System Update Sets"],"answer":[2],"explanation":"System Import Sets handles data imports from external sources.","multi":False},
            {"id":21,"question":"What is a key difference between Reporting and Performance Analytics?","options":["Performance Analytics data can be published to Dashboards; Reports cannot.","Reports can be run on a scheduled basis; Performance Analytics cannot.","Performance Analytics shows KPIs; Reporting does not.","Performance Analytics contains snapshots of data taken over time; Reporting shows only current data."],"answer":[3],"explanation":"Performance Analytics stores historical snapshots to analyze trends. Standard reports show real-time data only.","multi":False},
            {"id":22,"question":"Which of the following is used to categorize, flag, and locate records?","options":["Search","Favorites","Tags","Bookmarks"],"answer":[2],"explanation":"Tags allow users to categorize and easily retrieve records.","multi":False},
            {"id":23,"question":"What is the name of the conversational bot platform in ServiceNow?","options":["Connect Chat","Live Feed","Virtual Agent","Answer Agent"],"answer":[2],"explanation":"Virtual Agent is ServiceNow's chatbot platform for conversational self-service.","multi":False},
            {"id":24,"question":"Where can the user find notes for their incidents?","options":["Comments section","Notes section","Notes field","Description field"],"answer":[1],"explanation":"Notes are stored in the Notes related section on the incident form.","multi":False},
            {"id":25,"question":"How to combine data from two tables in a report?","options":["Join","Related Lists","Many to Many","Database View"],"answer":[3],"explanation":"Database Views allow reporting across multiple tables.","multi":False},
            {"id":26,"question":"What is a characteristic of importing data into ServiceNow?","options":["An existing Transform Map can be used one time on the same import set","Coalesce fields are used only after running Transform","Any user can manage and set up import sets","An existing Transform Map can be used multiple times on the same import set"],"answer":[3],"explanation":"Transform Maps can be reused to reprocess the same import set multiple times.","multi":False},
            {"id":27,"question":"The manager plans to send the same report every month to the client via email. What can help with this?","options":["Scheduled Report","Date/Time field on the report record","Scheduled Job","Schedule"],"answer":[0],"explanation":"Scheduled Reports automatically email reports at defined intervals.","multi":False},
            {"id":28,"question":"Which are valid ServiceNow User Authentication Methods? (Select 3 answers)","options":["FTP authentication","LDAP","SSO","Local Database","XML feed"],"answer":[1,2,3],"explanation":"ServiceNow supports LDAP, SSO, and internal Local Database authentication.","multi":True},
            {"id":29,"question":"The user has asked you to set up a completely new process. What will you use?","options":["Workflow","Flow","Business Rule","UI Policy"],"answer":[1],"explanation":"Flow Designer is the modern, no-code/low-code tool for creating new automated processes.","multi":False},
            {"id":30,"question":"What are examples of UI Actions relating to forms? (Select 3 answers)","options":["Form Buttons","Form View","Form Links","Form Context Menu","Form Columns"],"answer":[0,2,3],"explanation":"Form Buttons, Form Links, and Form Context Menu are all UI Action elements that appear on forms.","multi":True},
            {"id":31,"question":"Knowledge Base Search results can be sorted by which of the following? (Select 3 answers)","options":["Relevance","My group articles","Newest","Popularity","Views"],"answer":[0,2,4],"explanation":"Knowledge search results can be sorted by Relevance, Newest, and Views.","multi":True},
            {"id":32,"question":"Which database provides a logical model of your company infrastructure by identifying, controlling, maintaining and verifying CIs?","options":["CIBM","CSDM","ITSM","LDAP","CMDB"],"answer":[4],"explanation":"The CMDB stores and manages Configuration Items and their relationships.","multi":False},
            {"id":33,"question":"A customer wants to use a client script to validate things on a form before submission. What type of client script?","options":["onSubmit()","onLoad()","onSubmission()","onUpdate()"],"answer":[0],"explanation":"onSubmit() runs before the form is submitted and is correct for pre-submission validation.","multi":False},
            {"id":34,"question":"What module in the Service Catalog does an Administrator access to begin creating a new catalog item?","options":["Catalog Item","Maintain Items","Content Items","Items"],"answer":[1],"explanation":"Catalog Items are created and managed under the Maintain Items module.","multi":False},
            {"id":35,"question":"Which statement correctly describes the differences between a Client Script and a Business Rule?","options":["A Client Script executes on the server and a Business Rule executes on the client","A Client Script executes before a record is loaded and a Business Rule executes after a record is updated","A Client Script executes before a record is loaded and a Business Rule executes after a record is loaded","A Client Script executes on the client and a Business Rule executes on the server"],"answer":[3],"explanation":"Client Scripts run in the browser (client-side); Business Rules run on the server (server-side).","multi":False},
            {"id":36,"question":"How can the abbreviation CSDM be expanded?","options":["Common Service Data Model","Common System Database Model","Customer Service Data Model","Customer System Data Media"],"answer":[0],"explanation":"CSDM stands for Common Service Data Model.","multi":False},
            {"id":37,"question":"The ServiceNow platform includes which types of interfaces? (Select 3 answers)","options":["Field Service Taskboard","Back Office Dashboard","Service Portals","Now Mobile Apps","Agent Control Center","Now Platform® User Interfaces"],"answer":[2,3,5],"explanation":"ServiceNow supports Service Portals, Now Mobile Apps, and the Now Platform® User Interface.","multi":True},
            {"id":38,"question":"What sections do you need to fill in when creating a notification? (Select 3 answers)","options":["Notes","What it will contain","Who will receive","When to send","Who will send"],"answer":[1,2,3],"explanation":"A notification requires: Who will receive, When to send, and What it will contain.","multi":True},
            {"id":39,"question":"Which one of the following describes the primary operations performed against tables in ServiceNow?","options":["Create, Rate, Update, Delete","Create, Read, Write, Delete","Create, Read, Upload, Delete","Capture, Rate, Write, Develop"],"answer":[1],"explanation":"CRUD: Create, Read, Write (Update), Delete are the standard database operations.","multi":False},
            {"id":40,"question":"What action will allow you to personalize layouts of columns in a list?","options":["Context Menu > View > Personalize","Click Gear Icon > Personalize window options > Select the appropriate columns","Select the column > Click Edit icon > Choose options","Right-click header > Choose options"],"answer":[1],"explanation":"The gear icon in the list header allows users to personalize which columns are shown.","multi":False},
            {"id":41,"question":"Which tab on the knowledge base record would you use to identify users who are able to read articles?","options":["Can Read","Can Access","ACL","Accessible to"],"answer":[0],"explanation":"The 'Can Read' tab on the knowledge base record controls which users can read articles.","multi":False},
            {"id":42,"question":"Where can you create a flow?","options":["Process Automation > Flow Designer","Process Automation > Create Flow","Workflow > Flow Designer","Workflow > Workflow Editor"],"answer":[0],"explanation":"Flows are created in Flow Designer, accessed via Process Automation > Flow Designer.","multi":False},
            {"id":43,"question":"How are Workflows moved between instances?","options":["Workflows are moved using Update Sets","Workflows are moved using XML only","Workflows cannot be moved","Workflows are moved using Application Sets"],"answer":[0],"explanation":"Update Sets capture workflow configuration changes and move them between instances.","multi":False},
            {"id":44,"question":"While showing a customer their Incident form, they ask to change the Priority field title. How would you do that? (Select 2 answers)","options":["Right click Priority > Configure Column","Right click Priority > Configure Display Settings","Right click Priority > Configure Dictionary","Right click Priority > Configure Label"],"answer":[2,3],"explanation":"Dictionary controls field properties. Label changes the display text shown on forms.","multi":True},
            {"id":45,"question":"Which admin role is required to make changes to High Security Settings?","options":["acl_admin","admin","security_admin","sec_admin","hi_sec_admin"],"answer":[2],"explanation":"High Security Settings require the elevated security_admin role.","multi":False},
            {"id":46,"question":"What records can be created when placing an order in the Service Catalog? (Select 3 answers)","options":["Request [sc_request]","Problem Task [problem_task]","Change Request [change_request]","Requested Item [sc_req_item]","Catalog Task [sc_task]"],"answer":[0,3,4],"explanation":"A Service Catalog order creates a REQ > RITM > SCTASK hierarchy.","multi":True},
            {"id":47,"question":"What information does the System Dictionary contain?","options":["The definition for each table and column","The human-readable labels and language settings","The information on how tables relate","The language dictionary for spell checking"],"answer":[0],"explanation":"The System Dictionary defines all fields, their data types, and attributes for every table.","multi":False},
            {"id":48,"question":"What is the name of the 32-character unique key assigned to every record?","options":["ID","Sys ID","Key","Unique ID","System ID"],"answer":[1],"explanation":"Every ServiceNow record is assigned a globally unique 32-character Sys ID (sys_id).","multi":False},
            {"id":49,"question":"What ServiceNow feature allows you to include data from a secondary related table on a report?","options":["Outer Join","Join","Dot Walking","SQL"],"answer":[2],"explanation":"Dot walking traverses table relationships to retrieve fields from related tables.","multi":False},
            {"id":50,"question":"What do you activate when you want to add applications or functionality within your development instance?","options":["Update Set","App Package","Updated Pack","Patch","Plugin"],"answer":[4],"explanation":"Plugins are activated to enable additional applications and functionality.","multi":False},
            {"id":51,"question":"What are the components that make up a filter condition? (Select 3 answers)","options":["Field","Value","Column","Operator","Match Criteria"],"answer":[0,1,3],"explanation":"A filter condition is composed of: Field + Operator + Value.","multi":True},
            {"id":52,"question":"What process allows users to create, categorize, review, approve and browse important information in a centralized location?","options":["Knowledge-Centered Management","Knowledge Management","Information Portal Management","Self Service Management","Business Information Management"],"answer":[1],"explanation":"Knowledge Management handles the full lifecycle of knowledge articles.","multi":False},
            {"id":53,"question":"What controls the publishing and retiring process for knowledge articles?","options":["Approval Definitions","Workflow","Approval Policies","State Lifecycle","Workflow Designer"],"answer":[1],"explanation":"Knowledge workflows control the approval, publishing, and retiring states of knowledge articles.","multi":False},
            {"id":54,"question":"Which three Variable Types can be added to a Service Catalog Item?","options":["True/False, Checkbox, and Number List","Number List, Single Line Text, and Reference","True/False, Multiple Choice, and Ordered","Multiple Choice, Select Box, and Checkbox"],"answer":[3],"explanation":"Multiple Choice, Select Box, and Checkbox are valid Service Catalog variable types.","multi":False},
            {"id":55,"question":"How is a group defined in ServiceNow?","options":["A group defines users sharing location","A group defines users sharing job title","A group is stored in sys_user_group_type","A group is one record stored in the Group [sys_user_group] table"],"answer":[3],"explanation":"A group is a single record stored in the sys_user_group table.","multi":False},
            {"id":56,"question":"What will happen if you click 'Filter Out' on the 'Hardware' category on the incident list?","options":["Opens new window","Nothing happens","Hardware incidents remain visible","All incidents with Hardware category will disappear"],"answer":[3],"explanation":"'Filter Out' excludes those records from the current list view.","multi":False},
            {"id":57,"question":"What ServiceNow API will you use to retrieve incident data in a server script?","options":["GlideApi","GlideData","GlideRecord","g_form"],"answer":[2],"explanation":"GlideRecord is the server-side API used to query, create, update, and delete records.","multi":False},
            {"id":58,"question":"Which user will have access to all applications and will be able to bypass all security?","options":["sys_admin","superuser","admin","root"],"answer":[2],"explanation":"The admin user account in ServiceNow has full access and bypasses all security constraints.","multi":False},
            {"id":59,"question":"When using a reference field on a form, what does the magnifier icon do?","options":["Opens the record in a popup","Opens a dictionary entry for the field","Opens a list of selectable records for that field","Opens the related table"],"answer":[2],"explanation":"The magnifier/reference lookup button on a reference field opens a record picker to find and select the related record.","multi":False},
            {"id":60,"question":"What is the purpose of the 'Coalesce' field in a Transform Map?","options":["It deduplicates imported records by matching a field to existing records","It maps a source field to a target field","It validates data format before import","It creates a unique index on the target table"],"answer":[0],"explanation":"Coalesce is used to prevent duplicate records: if a match is found on the coalescing field, the existing record is updated instead of a new one being created.","multi":False},
        ]
    }
}

# ── Abbreviated stubs for tests 2, 3, 4 – the management command ──────────────
# will call a helper to fetch questions from the existing JS data via JSON import.
# For now, we embed test2/3/4 as empty so the command is complete; add stubs if needed.


class Command(BaseCommand):
    help = "Seeds all practice test questions into the SQLite database."

    def handle(self, *args, **kwargs):
        self.stdout.write("Loading questions into database...")

        for slug, data in TESTS_DATA.items():
            test, created = Test.objects.get_or_create(slug=slug, defaults={"name": data["name"]})
            if not created:
                test.name = data["name"]
                test.save()

            # Clear existing questions to allow re-seeding
            test.questions.all().delete()

            for q in data["questions"]:
                Question.objects.create(
                    test=test,
                    number=q["id"],
                    question=q["question"],
                    options=q["options"],
                    answer=q["answer"],
                    explanation=q.get("explanation", ""),
                    image=q.get("image", ""),
                    multi=q.get("multi", False),
                )

            self.stdout.write(f"  ✓ {test.name}: {len(data['questions'])} questions")

        self.stdout.write(self.style.SUCCESS("Done! All questions loaded."))
