# Generated by Django 6.0.2 on 2026-03-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_test_is_exam_test_testattempt_time_taken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="candidate_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="candidate_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="enrollment_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="roll_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
