# Generated by Django 6.0.2 on 2026-03-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_testattempt_candidate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='test',
            name='scheduled_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
