# Generated by Django 6.0.2 on 2026-03-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_test_duration_minutes_test_scheduled_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="enable_auto_ban",
            field=models.BooleanField(
                default=True,
                help_text="Auto-ban users after 3 violations. If disabled, only warnings are given.",
            ),
        ),
    ]
