# Generated by Django 6.0.2 on 2026-03-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_test_enable_auto_ban"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_ended",
            field=models.BooleanField(
                default=False,
                help_text="Admin marks test as ended. Review answers become available.",
            ),
        ),
    ]
