# Generated by Django 6.0.2 on 2026-03-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_test_is_ended"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="batch",
            field=models.CharField(
                blank=True, help_text="Batch (e.g., A, B, C)", max_length=10, null=True
            ),
        ),
    ]
